### ISSUE TITLE
command open scrcpy

### ISSUE THREAD

**Issue by Mark-Walen** [SimonAKing/scrcpy-gui#113]
[server] ERROR: Exception on thread Thread[main,5,main]
android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1967)
        at android.media.MediaCodec.configure(MediaCodec.java:1896)
        at com.genymobile.scrcpy.ScreenEncoder.configure(ScreenEncoder.java:157)
        at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:67)
        at com.genymobile.scrcpy.Server.scrcpy(Server.java:32)
        at com.genymobile.scrcpy.Server.main(Server.java:133)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:371)
Exit due to uncaughtException in main thread:
INFO: Initial texture: 1080x2336
WARN: Could not terminate server

**Comment by Mark-Walen** [comment]
my cellphone brand：huawei

**Comment by SimonAKing** [comment]
这个报告对应已经停止支持的 Scrcpy GUI 1.x / scrcpy 1.x。2.0 Beta 已重写 scrcpy 4.x 参数映射、可执行文件发现和进程状态判断，启动失败会在「Logs / 日志」中显示真实 stderr，不再提前提示成功。现归档旧版本报告；如果在 v2.0.0-beta.1 + scrcpy 4.x 上仍能复现，请使用新的 Bug Report 模板提交日志、系统和设备信息。
