### ISSUE TITLE
打开镜像失败

### ISSUE THREAD

**Issue by SX-Code** [SimonAKing/scrcpy-gui#95]
命令行使用scrcpy，出现以下错误，GUI连接失败，问题应该也在这
2021-01-21 20:24:32.408 scrcpy[92906:972790] CRITICAL: Could not initialize SDL: The video driver did not add any displays
[server] INFO: Device: Xiaomi MI 8 (Android 10)
[server] ERROR: Exception on thread Thread[main,5,main]
java.io.IOException: Connection refused
	at android.net.LocalSocketImpl.connectLocal(Native Method)
	at android.net.LocalSocketImpl.connect(LocalSocketImpl.java:296)
	at android.net.LocalSocket.connect(LocalSocket.java:147)
	at com.genymobile.scrcpy.DesktopConnection.connect(DesktopConnection.java:40)
	at com.genymobile.scrcpy.DesktopConnection.open(DesktopConnection.java:63)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:57)
	at com.genymobile.scrcpy.Server.main(Server.java:252)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:380)

**Comment by SimonAKing** [comment]
这个报告对应已经停止支持的 Scrcpy GUI 1.x / scrcpy 1.x。2.0 Beta 已重写 scrcpy 4.x 参数映射、可执行文件发现和进程状态判断，启动失败会在「Logs / 日志」中显示真实 stderr，不再提前提示成功。现归档旧版本报告；如果在 v2.0.0-beta.1 + scrcpy 4.x 上仍能复现，请使用新的 Bug Report 模板提交日志、系统和设备信息。
